services:
  minio1:
    image: bitnami/minio:latest
    # container_name: minio1
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DISTRIBUTED_MODE_ENABLED=no

      - MINIO_SCHEME=http
      # - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      #- MINIO_SKIP_CLIENT=yes
    # volumes:
    #   - minio1-data:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"  # Console UI
      
    # command: server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    command: server --address ":9000" --console-address ":9001" /bitnami/minio/data

    networks:
      - dwh_network

networks:
  dwh_network:
    driver: bridge